### ISSUE TITLE
是否方便更新下IP白名单PAC

### ISSUE THREAD

**Issue by GoogleGFW** [gaoyuzhe22/ssr-iplist#1]
https://github.com/breakwa11/gfw_whitelist/blob/master/whiteiplist.pac

这个PAC也两年没更新了。也没人管了。。主要是SS PC端不带白名单分流。配合扩展使用。

可能跟本项目SSR主题不相符，请谅解。。

**Comment by sharuijinfriend** [comment]
我根据ibug的改了一点，需要配合SwitchyOmega等插件使用。当然如果你想配合ss使用的话也可以，只需要把var proxy那行改掉就行了
https://raw.githubusercontent.com/sharuijinfriend/pac/master/out.pac

**Comment by hyy34** [comment]
好久没更新了，是否还用更新呢？还有如何配合SwitchyOmega使用呢？我现在用的是SSD！

**Comment by sharuijinfriend** [comment]
可以自行执行build.sh更新pac。SwitchyOmega只需新建一个pac模式，把pac文件中的内容复制进去即可

**Comment by hyy34** [comment]
> 可以自行执行build.sh更新pac。SwitchyOmega只需新建一个pac模式，把pac文件中的内容复制进去即可

build.sh更新pac 这个真是不太会？可否能简单指导下？我的意思是您的outpac好久没更新了，是不是现在没有什么可以更新的？
SwitchyOmega建pac模式这个也没有接触过，建立pac模式后，我的SSD也需要是pac模式，并且用这outpac吗？

**Comment by sharuijinfriend** [comment]
只需要在一台装了python3的linux机器上面，输入
`cd ~ && git clone https://github.com/sharuijinfriend/pac.git && cd pac && bash ./build.sh`
或者
`cd ~ && git clone https://github.com/sharuijinfriend/pac.git && cd pac && bash ./buildipv6direct.sh`
前者ipv6全部走代理，后者ipv6全部直连。对于ipv4都是国内外IP分流
SwitchyOmega教程网上很多了，你可以自己去看
